version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: bolson
      MYSQL_DATABASE: Ejemplo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  wazuh:
    build:
      context: .
      dockerfile: Dockerfile.wazuh
    ports:
      - "1514:1514/udp"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec

volumes:
  db_data:
  wazuh_data:
