version: "3.8"

services:
  web:
    image: asancar0801/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db

  db:
    image: asancar0801/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: bolson
      MYSQL_DATABASE: Ejemplo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  wazuh:
    image: asancar0801/wazuh:latest
    ports:
      - "1514:1514/udp"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec

volumes:
  db_data:
  wazuh_data:
